version: "3.7"
services:
  my-server1:
    image: my-server1
    build:
      context: server1
      dockerfile: Dockerfile
    container_name: "my-server1"
    privileged: true
    ports:
      - "10001:10001"
      - "20001:20001"

    stdin_open: true #相当于docker run 命令的-i
    tty: true #相当于docker run 命令的 -t

  my-server2:
    image: my-server2
    build:
      context: server2
      dockerfile: Dockerfile
    container_name: "my-server2"
    privileged: true
    ports:
      - "10002:10002"

    stdin_open: true #相当于docker run 命令的-i
    tty: true #相当于docker run 命令的 -t
