version: "3.7"
services:
  server1:
    volumes:
      - /home/web/web-deploy-test/server1:/home/web_project/web-deploy-test/server1
    networks:
      - cloud
    image: my-server1
    build:
      context: server1
      dockerfile: Dockerfile
    container_name: "my-server1"
    privileged: true
    depends_on:
      - server2 #依赖server2，也就是先启动server2
    expose:
      - "10001"
      - "20001"
    ports:
      - "10001:10001"
      - "20001:20001"

    tty: true

  server2:
    volumes:
      - /home/web/web-deploy-test/server2:/home/web_project/web-deploy-test/server2
    image: my-server2
    networks:
      - cloud
    build:
      context: server2
      dockerfile: Dockerfile
    container_name: "my-server2"
    privileged: true
    expose:
      - "10002"
      - "20002"
    ports:
      - "10002:10002"
      - "20002:20002"

    tty: true

#定义网络
networks:
  #网络名
  cloud:
    #有就使用，没有就会新建网络(默认bridge)
    external: false