version: '2'
services:
  server1:
    image: image-for-server1
    build: server1
    container_name: "my-server1"
    depends_on:
      - server2 #依赖server2，也就是先启动server2
    entrypoint:
      - java
      - -jar
      - ${JAVA_OPTS}
      - /app.jar
  server2:
    image: image-for-server2
    build: server2
    container_name: "my-server2"
    entrypoint:
      - java
      - -jar
      - ${JAVA_OPTS}
      - /app.jar